import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faInstagram , faTelegram } from '@fortawesome/free-brands-svg-icons'


const socials = [

	{
		id: 1,
		icon: faInstagram,
		link: "https://www.instagram.com/exclusive_developer",
		color: "#D0228B",
	},
	{
		id: 2,
		icon: faTelegram,
		link: "https://t.me/developerFrontEnd",
		color: "#1086C1",
	},
];

const Home: NextPage = () => {
	return (
		<div className={styles.container }>
			<Head>
				<title>Exclusive Software</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/app.ico" />
				<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
			</Head>

			<main className={styles.main}>
				<div className={styles.home_wrapper}>
					<div className={styles.data_home}>
						<div className={styles.content_home}>Exclusive Software</div>
            <div className={styles.socials}>
                {socials.map((item)=>(
                  <div><a href={item.link}><FontAwesomeIcon icon={item.icon} fontSize={"40"} key={item.id} /></a></div>
                ))}
           
            </div>
					</div>
					<div className={styles.container_wave}>
						<svg viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet">
							<path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style={{ stroke: "none", fill: "#222327" }}></path>
						</svg>
					</div>
				</div>
				
			</main>

		</div>
	);
};

export default Home;
{/* <div
onClick={() => {
  scrollTo({
    top: 1000,
    behavior: "smooth",
  });
}}
>
Down
</div> */}